"use client";

import * as React from "react";
import Link from "next/link";
import {
  AlertTriangle,
  ClipboardCheck,
  FileDown,
  Loader2,
  Mail,
  Printer,
  RefreshCw,
  Wand2,
} from "lucide-react";
import { toast } from "sonner";

import { EditableText } from "@/components/EditableText";
import { useWorkspace } from "@/components/WorkspaceProvider";
import { SaveVariantDialog } from "@/components/SaveVariantDialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";
import {
  claimedTerms,
  letterWordCount,
  setLetterParagraph,
  toCoverLetterText,
} from "@/lib/coverLetterGenerator";
import { EMPHASIS_LABELS } from "@/lib/types";
import { downloadBlob, slugify } from "@/lib/utils";

export default function CoverLetterPage() {
  const {
    profile,
    analysis,
    draft,
    coverLetter,
    generateLetter,
    setCoverLetterOptions,
    patchLetter,
    clearLetter,
    saveApplication,
  } = useWorkspace();
  const [scale, setScale] = React.useState(1);
  const [busy, setBusy] = React.useState(false);
  const [saveOpen, setSaveOpen] = React.useState(false);
  const [editing, setEditing] = React.useState(true);
  const wrapperRef = React.useRef<HTMLDivElement>(null);

  React.useEffect(() => {
    const element = wrapperRef.current;
    if (!element) return;
    const measure = () => setScale(Math.min(1, element.clientWidth / (8.5 * 96)));
    measure();
    const observer = new ResizeObserver(measure);
    observer.observe(element);
    return () => observer.disconnect();
  }, []);

  const words = coverLetter ? letterWordCount(coverLetter) : 0;
  const claimed = coverLetter ? claimedTerms(coverLetter, analysis) : [];
  const nameGaps = coverLetter ? coverLetter.options.nameGaps !== false : true;

  const generateLetterWithNameGaps = (next: boolean) => {
    setCoverLetterOptions({ nameGaps: next });
    toast.success(next ? "The letter now names your uncovered keywords." : "The letter no longer mentions them.");
  };

  const handleCopy = async () => {
    if (!coverLetter) return;
    try {
      await navigator.clipboard.writeText(toCoverLetterText(coverLetter, profile));
      toast.success("Letter copied as plain text.");
    } catch {
      toast.error("Clipboard write was blocked.");
    }
  };

  const handlePdf = async () => {
    if (!coverLetter) return;
    setBusy(true);
    try {
      const { pdf } = await import("@react-pdf/renderer");
      const { buildCoverLetterPdfDocument } = await import("@/components/ResumePdfDocument");
      const blob = await pdf(buildCoverLetterPdfDocument({ letter: coverLetter, profile })).toBlob();
      const structure = await blob.text();
      const pages = (structure.match(/\/Type\s*\/Page[^s]/g) ?? []).length;
      downloadBlob(
        blob,
        `${slugify(profile.header.name, "resume")}_cover-letter_${slugify(coverLetter.company, "company")}.pdf`,
      );
      if (pages > 1) {
        toast.warning(`That letter ran to ${pages} pages — trim a paragraph to keep it to one.`);
      } else {
        toast.success("Letter downloaded — one page, selectable text.");
      }
    } catch (error) {
      console.error(error);
      toast.error("Letter PDF failed. The Print button produces the same page.");
    } finally {
      setBusy(false);
    }
  };

  if (!analysis) {
    return (
      <div className="mx-auto max-w-3xl space-y-4 px-4 py-8">
        <Card>
          <CardHeader>
            <CardTitle>Cover letter</CardTitle>
            <CardDescription>
              The letter is built from the same job analysis as the resume, so load a posting first.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Button asChild size="sm">
              <Link href="/">Load a posting in the workspace</Link>
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="grid gap-4 px-4 py-4 lg:grid-cols-[minmax(0,400px)_minmax(0,1fr)] print:block print:p-0">
      <div className="space-y-3 print:hidden">
        <header className="space-y-1">
          <h1 className="flex items-center gap-2 text-lg font-semibold tracking-tight">
            <Mail className="h-4 w-4 text-primary" />
            Cover letter
          </h1>
          <p className="text-xs text-muted-foreground">
            Generated by the same engine as the resume, so every claim traces back to your profile —
            and the posting&apos;s gaps are named rather than faked.
          </p>
        </header>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm">{analysis.meta.title}</CardTitle>
            <CardDescription>
              {analysis.meta.company} · {analysis.meta.location} · {analysis.meta.workMode}
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            <div className="flex flex-wrap gap-1.5">
              <Badge variant="muted">
                {draft.intensity}% · {EMPHASIS_LABELS[draft.emphasis]}
              </Badge>
              {coverLetter ? <Badge variant="outline">{words} words</Badge> : null}
              <Badge variant={analysis.matchScore >= 70 ? "success" : "warn"}>
                {analysis.matchScore}% keyword match
              </Badge>
            </div>

            <div className="space-y-1">
              <Label htmlFor="to-name">Addressed to</Label>
              <Input
                id="to-name"
                value={coverLetter?.toName ?? ""}
                placeholder="Hiring Manager"
                onChange={(event) =>
                  patchLetter((current) => ({
                    ...current,
                    toName: event.target.value,
                    salutation: `Dear ${event.target.value || "Hiring Manager"},`,
                  }))
                }
                className="h-8 text-xs"
              />
            </div>

            <div className="flex flex-wrap gap-2">
              <Button
                size="sm"
                onClick={() => {
                  generateLetter();
                  toast.success("Letter generated from your profile and this posting.");
                }}
              >
                {coverLetter ? <RefreshCw className="h-4 w-4" /> : <Wand2 className="h-4 w-4" />}
                {coverLetter ? "Regenerate" : "Generate letter"}
              </Button>
              <Button
                size="sm"
                variant="outline"
                disabled={!coverLetter}
                onClick={() => setSaveOpen(true)}
              >
                Save as variant
              </Button>
              <SaveVariantDialog
                open={saveOpen}
                onOpenChange={setSaveOpen}
                jobTitle={analysis?.meta.title ?? "this role"}
                company={analysis?.meta.company ?? ""}
                description={
                  <>
                    Saves the tailored resume <span className="font-medium text-foreground">and
                    this cover letter</span> as one variant. The dates here are what the follow-up
                    calendar will use.
                  </>
                }
                onSave={(details) => {
                  saveApplication({ ...details, notes: details.notes || "Saved with cover letter" });
                  toast.success("Letter and resume saved as a variant.");
                }}
              />
              {coverLetter ? (
                <Button size="sm" variant="ghost" onClick={clearLetter}>
                  Clear
                </Button>
              ) : null}
            </div>

            <div className="flex items-center gap-2 rounded-md border p-2 text-[11px]">
              <label htmlFor="letter-edit" className="cursor-pointer select-none font-medium">
                Edit in place
              </label>
              <input
                id="letter-edit"
                type="checkbox"
                checked={editing}
                onChange={(event) => setEditing(event.target.checked)}
                className="h-3.5 w-3.5"
              />
              <span className="text-muted-foreground">Same formatting, no reformatting.</span>
            </div>

            <div className="flex items-start gap-2 rounded-md border p-2 text-[11px]">
              <input
                id="letter-gaps"
                type="checkbox"
                checked={nameGaps}
                disabled={!coverLetter}
                onChange={() => generateLetterWithNameGaps(!nameGaps)}
                className="mt-0.5 h-3.5 w-3.5"
              />
              <label htmlFor="letter-gaps" className="cursor-pointer select-none">
                <span className="font-medium">Name the uncovered keywords</span>
                <span className="block text-muted-foreground">
                  On: one paragraph says plainly which posting terms are not on your resume. Off: the
                  letter never mentions them, so a keyword scanner cannot see them at all.
                </span>
              </label>
            </div>
          </CardContent>
        </Card>

        {coverLetter ? (
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm">What the letter used</CardTitle>
              <CardDescription>
                {coverLetter.notes.length} decision(s) and {claimed.length} posting term(s) claimed
                from profile evidence.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-3">
              <ul className="space-y-1 text-[11px] leading-relaxed text-muted-foreground">
                {coverLetter.notes.map((note, index) => (
                  <li key={index} className="flex gap-1.5">
                    <span className="text-primary">•</span>
                    <span>{note}</span>
                  </li>
                ))}
              </ul>

              <Separator />

              <div className="space-y-1">
                <p className="text-[11px] font-medium">Posting terms the letter claims</p>
                <div className="flex flex-wrap gap-1">
                  {claimed.length ? (
                    claimed.map((term) => (
                      <Badge key={term} variant="success" className="text-[10px]">
                        {term}
                      </Badge>
                    ))
                  ) : (
                    <span className="text-[11px] text-muted-foreground">
                      None — the letter stayed general.
                    </span>
                  )}
                </div>
              </div>

              <div className="space-y-1">
                <p className="text-[11px] font-medium">Gaps the letter names instead of claiming</p>
                <div className="flex flex-wrap gap-1">
                  {coverLetter.gapsNotClaimed.length ? (
                    coverLetter.gapsNotClaimed.map((term) => (
                      <Badge key={term} variant="warn" className="text-[10px]">
                        {term}
                      </Badge>
                    ))
                  ) : (
                    <span className="text-[11px] text-muted-foreground">
                      Nothing uncovered in this posting.
                    </span>
                  )}
                </div>
                <p className="flex items-start gap-1.5 pt-1 text-[10px] text-muted-foreground">
                  <AlertTriangle className="mt-0.5 h-3 w-3 shrink-0" />
                  The generator cannot insert these terms at any intensity. If you are genuinely
                  acquiring one, add it to the Master Profile and regenerate.
                </p>
              </div>
            </CardContent>
          </Card>
        ) : (
          <Card>
            <CardHeader>
              <CardTitle className="text-sm">No letter yet</CardTitle>
              <CardDescription>
                Generate one from this posting: why this role, two pieces of verbatim evidence from
                your profile, and logistics. Longer and more posting-specific at higher intensity.
              </CardDescription>
            </CardHeader>
          </Card>
        )}

      </div>

      <div className="space-y-3 print:static print:overflow-visible">
        <div className="flex flex-wrap items-center gap-2 print-hide">
          <div className="text-xs font-medium">Letter preview</div>
          {coverLetter ? (
            <>
              <Badge variant="muted">
                {scale < 1 ? `scaled ${Math.round(scale * 100)}%` : "actual size"}
              </Badge>
              <div className="ml-auto flex items-center gap-2">
                <Button size="sm" variant="outline" onClick={handleCopy}>
                  <ClipboardCheck className="h-4 w-4" />
                  Copy text
                </Button>
                <Button size="sm" variant="outline" onClick={() => window.print()}>
                  <Printer className="h-4 w-4" />
                  Print
                </Button>
                <Button size="sm" onClick={handlePdf} disabled={busy}>
                  {busy ? (
                    <Loader2 className="h-4 w-4 animate-spin" />
                  ) : (
                    <FileDown className="h-4 w-4" />
                  )}
                  Download PDF
                </Button>
              </div>
            </>
          ) : null}
        </div>

        <div ref={wrapperRef} className="w-full print:static print:overflow-visible">
          <div
            className="relative w-full print:static print:h-auto"
            style={{ height: `calc(11in * ${scale})` }}
          >
            {coverLetter ? (
              <div
                className="letter-sheet sheet-shell print-sheet absolute left-0 top-0"
                style={{ transform: `scale(${scale})`, transformOrigin: "top left" }}
              >
                <div className="sender">
                  <div className="name">{profile.header.name}</div>
                  <div className="contact">
                    {[
                      profile.header.locationNote || profile.header.location,
                      profile.header.email,
                      profile.header.phone,
                      profile.header.linkedin,
                    ]
                      .filter(Boolean)
                      .join("  ·  ")}
                  </div>
                </div>

                <div className="meta">
                  {new Date(coverLetter.generatedAt).toLocaleDateString(undefined, {
                    month: "long",
                    day: "numeric",
                    year: "numeric",
                  })}
                  <br />
                  Hiring Team
                  <br />
                  {coverLetter.company}
                  {coverLetter.location ? (
                    <>
                      <br />
                      {coverLetter.location}
                    </>
                  ) : null}
                </div>

                <div className="salutation">{coverLetter.salutation}</div>

                {coverLetter.paragraphs.map((paragraph) => (
                  <EditableText
                    key={paragraph.id}
                    as="p"
                    className="body"
                    multiline
                    value={paragraph.text}
                    editable={editing}
                    placeholder="Paragraph"
                    onCommit={(next) =>
                      patchLetter((current) => setLetterParagraph(current, paragraph.id, next))
                    }
                  />
                ))}

                <div className="closing">Sincerely,</div>
                <div className="signature">{profile.header.name}</div>
              </div>
            ) : (
              <div className="flex h-64 items-center justify-center rounded-lg border border-dashed text-xs text-muted-foreground print:hidden">
                Generate a letter to see it here, laid out on letter paper.
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
