/* -------------------------------------------------------------------------- */
/* The workspace as a folder of files                                         */
/*                                                                            */
/* Everything else in this app lives in the browser: the profile, the draft,   */
/* the applications and the portfolio in `localStorage`, the picture bytes in  */
/* IndexedDB. That is local and private, and it is also invisible — clearing   */
/* the browser's site data takes all of it, and there is nothing to copy to a  */
/* USB stick.                                                                  */
/*                                                                            */
/* This module is the other half: a folder you choose, holding               */
/*                                                                            */
/*   workspace.json      the same bundle Export writes, kept up to date        */
/*   images/<id>.<ext>   the picture bytes, written once each                  */
/*                                                                            */
/* A *folder* rather than one file, which is the whole design decision here:   */
/* a single JSON with the pictures inside it would be base64 — a third bigger  */
/* than the bytes, and rewritten in full on every save. A portfolio with ten   */
/* photographs would mean writing megabytes on every keystroke-shaped change.  */
/* With a folder, `workspace.json` stays a couple of hundred kilobytes, the    */
/* images are written when they arrive and never again, and the whole thing    */
/* is one directory you can drag to a backup drive.                            */
/*                                                                            */
/* `showDirectoryPicker` is the browser API that makes this possible, and it   */
/* is Chromium-only: Chrome, Edge, Brave, Vivaldi. Safari and Firefox have no  */
/* equivalent, so the panel that uses this falls back to the Export/Import     */
/* JSON it has always had, and says so rather than hiding the button.          */
/* -------------------------------------------------------------------------- */

import { imageStore, type StoredImage } from "./imageStore";

/**
 * The folder picker, declared here because this TypeScript version's DOM types predate it.
 *
 * Deliberately narrow: only the shape this app calls, so nothing here pretends to describe the whole API.
 */
declare global {
  interface Window {
    showDirectoryPicker?: (options?: {
      id?: string;
      mode?: "read" | "readwrite";
      startIn?: "documents" | "desktop" | "downloads" | "music" | "pictures" | "videos";
    }) => Promise<FileSystemDirectoryHandle>;
  }

  /** Declared here too: this TypeScript version's DOM types predate iterating a directory. */
  interface FileSystemDirectoryHandle {
    values(): AsyncIterableIterator<FileSystemDirectoryHandle | FileSystemFileHandle>;
  }
}


/** The bundle's file name inside the folder, and the pictures' directory. */
export const WORKSPACE_FILE_NAME = "workspace.json";
export const IMAGE_DIRECTORY = "images";

/** Whether this browser can hand the app a folder to write to. */
export function supportsWorkspaceFolder(): boolean {
  return typeof window !== "undefined" && typeof window.showDirectoryPicker === "function";
}

/** `images/<id>.<ext>` — the id is the name, the extension is what the file is. */
export function imageFileName(id: string, type: string): string {
  const extension =
    type === "image/png" ? "png" : type === "image/webp" ? "webp" : type === "image/gif" ? "gif" : "jpg";
  return `${safeId(id)}.${extension}`;
}

/** The id back out of a file name, whatever its extension. */
export function imageIdFromFileName(fileName: string): string {
  return fileName.replace(/\.[a-z0-9]+$/i, "");
}

/** Ids are generated by the app, but a name that came from elsewhere gets cleaned before it is a path. */
function safeId(id: string): string {
  return id.replace(/[^a-zA-Z0-9._-]/g, "_").slice(0, 80) || "image";
}

/* -------------------------------------------------------------------------- */
/* Permission                                                                 */
/* -------------------------------------------------------------------------- */

export type FolderMode = "read" | "readwrite";

/**
 * Whether the folder is already usable, without asking.
 *
 * A remembered handle comes back from a previous visit *un*-permitted: the browser keeps the reference and makes
 * the app ask again, from a click. This is the check that decides which of those two states the panel is in.
 */
export async function folderPermission(folder: FileSystemDirectoryHandle, mode: FolderMode): Promise<boolean> {
  const handle = folder as FileSystemDirectoryHandle & {
    queryPermission?: (descriptor: { mode: FolderMode }) => Promise<PermissionState>;
  };
  if (!handle.queryPermission) return true;
  try {
    return (await handle.queryPermission({ mode })) === "granted";
  } catch {
    return false;
  }
}

/** Ask for permission. Must be called from a click — the browser will refuse it otherwise. */
export async function requestFolderPermission(
  folder: FileSystemDirectoryHandle,
  mode: FolderMode,
): Promise<boolean> {
  const handle = folder as FileSystemDirectoryHandle & {
    requestPermission?: (descriptor: { mode: FolderMode }) => Promise<PermissionState>;
  };
  if (!handle.requestPermission) return true;
  try {
    return (await handle.requestPermission({ mode })) === "granted";
  } catch {
    return false;
  }
}

/** The folder picker. Returns null when the person closes it rather than choosing. */
export async function chooseWorkspaceFolder(): Promise<FileSystemDirectoryHandle | null> {
  const picker = typeof window === "undefined" ? undefined : window.showDirectoryPicker;
  if (!picker) return null;
  try {
    return await picker({
      id: "career-matrix-workspace",
      mode: "readwrite",
      startIn: "documents",
    });
  } catch {
    return null;
  }
}

/* -------------------------------------------------------------------------- */
/* Reading and writing                                                        */
/* -------------------------------------------------------------------------- */

/** The bundle as it is stored in the folder, or null when the folder has no `workspace.json` yet. */
export async function readWorkspaceFile(folder: FileSystemDirectoryHandle): Promise<string | null> {
  try {
    const handle = await folder.getFileHandle(WORKSPACE_FILE_NAME);
    const file = await handle.getFile();
    return await file.text();
  } catch {
    return null;
  }
}

/** Writes the bundle. Every save is a full rewrite of one small file, which is the point of the folder. */
export async function writeWorkspaceFile(folder: FileSystemDirectoryHandle, text: string): Promise<void> {
  const handle = await folder.getFileHandle(WORKSPACE_FILE_NAME, { create: true });
  const writable = await handle.createWritable();
  await writable.write(text);
  await writable.close();
}

/**
 * Copies any picture the folder does not have yet, and says how many it wrote.
 *
 * Only missing files are written, which is what keeps a save cheap: the images are the large part and they never
 * change once imported. A file that is already there is left alone — even if it is a different size — because
 * rewriting pixels that have not changed is how a "save" turns into a stall.
 */
export async function syncWorkspaceImages(folder: FileSystemDirectoryHandle): Promise<number> {
  const stored = await imageStore.list();
  if (!stored.length) return 0;
  const directory = await folder.getDirectoryHandle(IMAGE_DIRECTORY, { create: true });

  let written = 0;
  for (const image of stored) {
    const name = imageFileName(image.id, image.type);
    try {
      await directory.getFileHandle(name);
      continue;
    } catch {
      // Not there yet, so write it.
    }
    const handle = await directory.getFileHandle(name, { create: true });
    const writable = await handle.createWritable();
    await writable.write(image.blob);
    await writable.close();
    written += 1;
  }
  return written;
}

/**
 * The pictures in the folder, back as images the store can hold.
 *
 * The names carry the ids and the extension carries the type, so the folder needs no manifest: what is in
 * `images/` is what came out of the app, and a file somebody dropped in there by hand is skipped rather than
 * guessed at.
 */
export async function readWorkspaceImages(folder: FileSystemDirectoryHandle): Promise<StoredImage[]> {
  let directory: FileSystemDirectoryHandle;
  try {
    directory = await folder.getDirectoryHandle(IMAGE_DIRECTORY);
  } catch {
    return [];
  }

  const images: StoredImage[] = [];
  for await (const entry of directory.values()) {
    if (entry.kind !== "file") continue;
    const name = entry.name;
    if (!/\.(jpe?g|png|webp|gif)$/i.test(name)) continue;
    const file = await (entry as FileSystemFileHandle).getFile();
    images.push({
      id: imageIdFromFileName(name),
      name,
      type: file.type || "image/jpeg",
      width: 0,
      height: 0,
      bytes: file.size,
      blob: file,
      createdAt: new Date(file.lastModified || Date.now()).toISOString(),
    });
  }
  return images;
}

/* -------------------------------------------------------------------------- */
/* Remembering the folder                                                     */
/* -------------------------------------------------------------------------- */

/**
 * The folder the app was last pointed at.
 *
 * A `FileSystemDirectoryHandle` cannot go in `localStorage` — it is not a string — but IndexedDB stores it by
 * reference, which is how the app can offer "reconnect to Career Matrix" on a later visit instead of making
 * somebody find the folder again. It comes back *un*-permitted, by design: the browser makes the app ask again
 * from a click, so a remembered handle is never a licence to write to a folder unattended.
 */
const HANDLE_DB = "career-matrix-workspace";
const HANDLE_STORE = "folders";

function handleDb(): Promise<IDBDatabase | null> {
  if (typeof indexedDB === "undefined") return Promise.resolve(null);
  return new Promise((resolve) => {
    const request = indexedDB.open(HANDLE_DB, 1);
    request.onupgradeneeded = () => {
      const db = request.result;
      if (!db.objectStoreNames.contains(HANDLE_STORE)) db.createObjectStore(HANDLE_STORE);
    };
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => resolve(null);
  });
}

/** Remembers the folder, or forgets it when passed null. */
export async function rememberFolder(folder: FileSystemDirectoryHandle | null): Promise<void> {
  const db = await handleDb();
  if (!db) return;
  await new Promise<void>((resolve) => {
    const transaction = db.transaction(HANDLE_STORE, "readwrite");
    const store = transaction.objectStore(HANDLE_STORE);
    if (folder) store.put(folder, "workspace");
    else store.delete("workspace");
    transaction.oncomplete = () => {
      db.close();
      resolve();
    };
    transaction.onerror = () => {
      db.close();
      resolve();
    };
  });
}

/** The remembered folder, if there is one. Permission is a separate question — see `folderPermission`. */
export async function recallFolder(): Promise<FileSystemDirectoryHandle | null> {
  const db = await handleDb();
  if (!db) return null;
  return new Promise((resolve) => {
    const transaction = db.transaction(HANDLE_STORE, "readonly");
    const request = transaction.objectStore(HANDLE_STORE).get("workspace");
    request.onsuccess = () => {
      const value = request.result as FileSystemDirectoryHandle | undefined;
      db.close();
      resolve(value ?? null);
    };
    request.onerror = () => {
      db.close();
      resolve(null);
    };
  });
}
